### ISSUE TITLE
android PAI机制

### ISSUE THREAD

**Issue by Plihuo** [wossoneri/wossoneri.github.io#14]
你好，能把你有的android PAI机制的google官方文件共享一份给我吗？最近刚好需要这个，但是相关的文档少之又少。刚好看到你的博客有这个东西。
谢谢啦。

**Comment by wossoneri** [comment]
> 你好，能把你有的android PAI机制的google官方文件共享一份给我吗？最近刚好需要这个，但是相关的文档少之又少。刚好看到你的博客有这个东西。
> 谢谢啦。

抱歉换工作了  这种文档现在没有了
